import type { Product } from '@/types/product';
import type { Collection } from '@/types/collection';
import type { JournalArticle } from '@/types/journal';

/**
 * Temporary in-repo data source, shaped exactly like the real Product /
 * Collection / JournalArticle types. This exists so the UI is driven by
 * typed data instead of hardcoded JSX — when a real backend/CMS is
 * introduced, only this module (or its call sites in a data-fetching
 * layer) needs to change, not the components that consume it.
 */

const now = new Date().toISOString();

function placeholderImage(id: string, alt: string): Product['gallery'][number] {
  return { id, src: '', alt, width: 1200, height: 1600 };
}

export const products: Product[] = [
  {
    id: 'silk-scarf-1',
    name: 'Silk Scarf N°1',
    slug: 'silk-scarf-1',
    category: 'scarves',
    price: 240,
    currency: 'USD',
    description: 'A signature silk scarf from the RULLIÉ Nocturne collection.',
    story:
      'Born from the interplay of shadow and light, this scarf carries the Nocturne collection\u2019s architectural print in hand-finished mulberry silk.',
    material: '100% Mulberry Silk',
    careInstructions: ['Dry clean only', 'Store flat, away from direct sunlight', 'Avoid contact with perfume or alcohol-based products'],
    gallery: [placeholderImage('silk-scarf-1-1', 'Silk Scarf N°1')],
    videos: [],
    collection: 'nocturne',
    relatedProducts: ['silk-scarf-2', 'signature-belt-noir', 'crescent-brooch'],
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: false,
    shopierUrl: '',
    seo: { title: 'Silk Scarf N°1 | RULLIÉ', description: 'A signature silk scarf from the RULLIÉ Nocturne collection.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'silk-scarf-2',
    name: 'Silk Scarf N°2',
    slug: 'silk-scarf-2',
    category: 'scarves',
    price: 240,
    currency: 'USD',
    description: 'A signature silk scarf from the RULLIÉ Nocturne collection.',
    story: 'A quieter companion piece to N\u00b01, rendered in a deeper tonal palette.',
    material: '100% Mulberry Silk',
    careInstructions: ['Dry clean only', 'Store flat, away from direct sunlight'],
    gallery: [placeholderImage('silk-scarf-2-1', 'Silk Scarf N°2')],
    videos: [],
    collection: 'nocturne',
    relatedProducts: ['silk-scarf-1', 'signature-belt-ivory'],
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: false,
    shopierUrl: '',
    seo: { title: 'Silk Scarf N°2 | RULLIÉ', description: 'A signature silk scarf from the RULLIÉ Nocturne collection.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'silk-scarf-3',
    name: 'Silk Scarf N°3',
    slug: 'silk-scarf-3',
    category: 'scarves',
    price: 240,
    currency: 'USD',
    description: 'A signature silk scarf from the RULLIÉ core collection.',
    story: 'Part of the year-round core line, designed to anchor a RULLIÉ wardrobe in every season.',
    material: '100% Mulberry Silk',
    careInstructions: ['Dry clean only', 'Store flat, away from direct sunlight'],
    gallery: [placeholderImage('silk-scarf-3-1', 'Silk Scarf N°3')],
    videos: [],
    relatedProducts: ['silk-scarf-4', 'signature-belt-onyx'],
    stockStatus: 'low_stock',
    isFeatured: true,
    isNew: false,
    shopierUrl: '',
    seo: { title: 'Silk Scarf N°3 | RULLIÉ', description: 'A signature silk scarf from the RULLIÉ core collection.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'silk-scarf-4',
    name: 'Silk Scarf N°4',
    slug: 'silk-scarf-4',
    category: 'scarves',
    price: 240,
    currency: 'USD',
    description: 'A signature silk scarf from the RULLIÉ core collection.',
    story: 'The newest addition to the core silk line.',
    material: '100% Mulberry Silk',
    careInstructions: ['Dry clean only', 'Store flat, away from direct sunlight'],
    gallery: [placeholderImage('silk-scarf-4-1', 'Silk Scarf N°4')],
    videos: [],
    relatedProducts: ['silk-scarf-3', 'crescent-brooch'],
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: true,
    shopierUrl: '',
    seo: { title: 'Silk Scarf N°4 | RULLIÉ', description: 'A signature silk scarf from the RULLIÉ core collection.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'signature-belt-noir',
    name: 'Signature Belt',
    slug: 'signature-belt-noir',
    category: 'belts',
    price: 180,
    currency: 'USD',
    description: 'Noir / Gold',
    story: 'Full-grain leather finished with a hand-polished brass buckle.',
    material: 'Full-grain leather, brass hardware',
    careInstructions: ['Wipe clean with a soft, dry cloth', 'Avoid prolonged exposure to moisture'],
    gallery: [placeholderImage('signature-belt-noir-1', 'Signature Belt — Noir / Gold')],
    videos: [],
    relatedProducts: ['silk-scarf-1', 'signature-belt-ivory'],
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: false,
    shopierUrl: '',
    seo: { title: 'Signature Belt — Noir / Gold | RULLIÉ', description: 'Full-grain leather belt, Noir / Gold.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'signature-belt-ivory',
    name: 'Signature Belt',
    slug: 'signature-belt-ivory',
    category: 'belts',
    price: 180,
    currency: 'USD',
    description: 'Ivory / Silver',
    story: 'Full-grain leather finished with a hand-polished silver buckle.',
    material: 'Full-grain leather, silver-tone hardware',
    careInstructions: ['Wipe clean with a soft, dry cloth', 'Avoid prolonged exposure to moisture'],
    gallery: [placeholderImage('signature-belt-ivory-1', 'Signature Belt — Ivory / Silver')],
    videos: [],
    relatedProducts: ['silk-scarf-2', 'signature-belt-noir'],
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: false,
    shopierUrl: '',
    seo: { title: 'Signature Belt — Ivory / Silver | RULLIÉ', description: 'Full-grain leather belt, Ivory / Silver.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'signature-belt-onyx',
    name: 'Signature Belt',
    slug: 'signature-belt-onyx',
    category: 'belts',
    price: 180,
    currency: 'USD',
    description: 'Onyx / Bronze',
    story: 'Full-grain leather finished with a hand-polished bronze buckle.',
    material: 'Full-grain leather, bronze hardware',
    careInstructions: ['Wipe clean with a soft, dry cloth', 'Avoid prolonged exposure to moisture'],
    gallery: [placeholderImage('signature-belt-onyx-1', 'Signature Belt — Onyx / Bronze')],
    videos: [],
    relatedProducts: ['silk-scarf-3', 'signature-belt-noir'],
    stockStatus: 'out_of_stock',
    isFeatured: false,
    isNew: false,
    shopierUrl: '',
    seo: { title: 'Signature Belt — Onyx / Bronze | RULLIÉ', description: 'Full-grain leather belt, Onyx / Bronze.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'crescent-brooch',
    name: 'Crescent Brooch',
    slug: 'crescent-brooch',
    category: 'brooches',
    price: 95,
    currency: 'USD',
    description: 'A sculptural brooch in brushed gold.',
    story: 'Inspired by the architectural forms of the Nocturne collection.',
    material: 'Brushed gold-plated brass',
    careInstructions: ['Store in the provided pouch', 'Avoid contact with water and perfume'],
    gallery: [placeholderImage('crescent-brooch-1', 'Crescent Brooch')],
    videos: [],
    collection: 'nocturne',
    relatedProducts: ['silk-scarf-1', 'silk-hair-tie'],
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    shopierUrl: '',
    seo: { title: 'Crescent Brooch | RULLIÉ', description: 'A sculptural brooch in brushed gold.' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'silk-hair-tie',
    name: 'Silk Hair Tie',
    slug: 'silk-hair-tie',
    category: 'accessories',
    price: 45,
    currency: 'USD',
    description: 'A soft, no-crease silk hair tie.',
    story: 'Made from the same mulberry silk as the core scarf line.',
    material: '100% Mulberry Silk',
    careInstructions: ['Hand wash cold', 'Lay flat to dry'],
    gallery: [placeholderImage('silk-hair-tie-1', 'Silk Hair Tie')],
    videos: [],
    relatedProducts: ['silk-scarf-3', 'crescent-brooch'],
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    shopierUrl: '',
    seo: { title: 'Silk Hair Tie | RULLIÉ', description: 'A soft, no-crease silk hair tie.' },
    createdAt: now,
    updatedAt: now,
  },
];

export const featuredProducts = products.filter((p) => p.isFeatured);
export const crossSellProducts = products.filter((p) => p.category === 'belts');

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}


export function getRelatedProducts(product: Product): Product[] {
  return product.relatedProducts
    .map((slug) => getProductBySlug(slug))
    .filter((p): p is Product => Boolean(p));
}

export const collections: Collection[] = [
  {
    id: 'nocturne',
    name: 'Nocturne',
    slug: 'nocturne',
    description: 'A symphony of shadows and light. Silk and statement pieces designed for the modern muse.',
    heroImage: '',
    mood: 'modern',
    products: products.filter((p) => p.collection === 'nocturne').map((p) => p.slug),
    editorialStory:
      'Nocturne draws on architectural forms and fluid silk drapery, exploring the space between structure and softness.',
    season: 'Fall/Winter',
    year: 2026,
    isActive: true,
    seo: { title: 'Nocturne Collection | RULLIÉ', description: 'A symphony of shadows and light.' },
    createdAt: now,
  },
  {
    id: 'daylight',
    name: 'Daylight',
    slug: 'daylight',
    description: 'Lightweight silhouettes and warm, sunlit tones for the season ahead.',
    heroImage: '',
    mood: 'warm',
    products: [],
    editorialStory: 'Daylight is an ongoing exploration of ease — pieces meant to move with you.',
    season: 'Spring/Summer',
    year: 2027,
    isActive: false,
    seo: { title: 'Daylight Collection | RULLIÉ', description: 'Lightweight silhouettes for the season ahead.' },
    createdAt: now,
  },
];

export function getCollectionBySlug(slug: string): Collection | undefined {
  return collections.find((c) => c.slug === slug);
}

export const journalArticles: JournalArticle[] = [
  {
    id: 'journal-1',
    title: 'The Making of Nocturne',
    slug: 'the-making-of-nocturne',
    category: 'design',
    tags: ['design', 'nocturne'],
    excerpt: 'An inside look at the architectural forms and fluid silk drapery behind the Nocturne collection.',
    content: '',
    author: { id: 'rullie-editorial', name: 'RULLIÉ Editorial' },
    publishedAt: now,
    readingTime: 5,
    coverImage: '',
    coverImageAlt: 'The Making of Nocturne',
    relatedProducts: ['silk-scarf-1', 'silk-scarf-2'],
    relatedArticles: ['modern-architecture-and-fashion'],
    isFeatured: true,
    seo: { title: 'The Making of Nocturne | RULLIÉ Journal', description: 'An inside look at the Nocturne collection.' },
  },
  {
    id: 'journal-2',
    title: 'Modern Architecture & Fashion',
    slug: 'modern-architecture-and-fashion',
    category: 'culture',
    tags: ['culture', 'design'],
    excerpt: 'How architectural thinking shapes the way we design silhouettes and prints.',
    content: '',
    author: { id: 'rullie-editorial', name: 'RULLIÉ Editorial' },
    publishedAt: now,
    readingTime: 4,
    coverImage: '',
    coverImageAlt: 'Modern Architecture & Fashion',
    relatedProducts: [],
    relatedArticles: ['the-making-of-nocturne'],
    isFeatured: false,
    seo: { title: 'Modern Architecture & Fashion | RULLIÉ Journal', description: 'How architecture shapes our designs.' },
  },
  {
    id: 'journal-3',
    title: 'Our Promise to the Planet',
    slug: 'our-promise-to-the-planet',
    category: 'sustainability',
    tags: ['sustainability'],
    excerpt: 'Our approach to responsibly sourced materials and long-lasting craftsmanship.',
    content: '',
    author: { id: 'rullie-editorial', name: 'RULLIÉ Editorial' },
    publishedAt: now,
    readingTime: 6,
    coverImage: '',
    coverImageAlt: 'Our Promise to the Planet',
    relatedProducts: [],
    relatedArticles: [],
    isFeatured: false,
    seo: { title: 'Our Promise to the Planet | RULLIÉ Journal', description: 'Our approach to sustainability.' },
  },
  {
    id: 'journal-4',
    title: 'How to Wear a Silk Scarf',
    slug: 'how-to-wear-a-silk-scarf',
    category: 'styling',
    tags: ['styling'],
    excerpt: 'From classic neck ties to modern top styles — versatile ways to wear our signature silks.',
    content: '',
    author: { id: 'rullie-editorial', name: 'RULLIÉ Editorial' },
    publishedAt: now,
    readingTime: 3,
    coverImage: '',
    coverImageAlt: 'How to Wear a Silk Scarf',
    relatedProducts: ['silk-scarf-1', 'silk-scarf-3'],
    relatedArticles: [],
    isFeatured: false,
    seo: { title: 'How to Wear a Silk Scarf | RULLIÉ Journal', description: 'Versatile ways to wear our signature silks.' },
  },
  {
    id: 'journal-5',
    title: 'The Art of Adornment',
    slug: 'art-of-adornment',
    category: 'editorial',
    tags: ['editorial'],
    excerpt: 'The inspiration behind our latest accessories line.',
    content: '',
    author: { id: 'rullie-editorial', name: 'RULLIÉ Editorial' },
    publishedAt: now,
    readingTime: 4,
    coverImage: '',
    coverImageAlt: 'The Art of Adornment',
    relatedProducts: ['crescent-brooch'],
    relatedArticles: [],
    isFeatured: false,
    seo: { title: 'The Art of Adornment | RULLIÉ Journal', description: 'The inspiration behind our accessories line.' },
  },
];

export const journalPreview = journalArticles.slice(0, 3);

export function getJournalArticleBySlug(slug: string): JournalArticle | undefined {
  return journalArticles.find((a) => a.slug === slug);
}
